#ifndef RETURN_VALUES_H
#define RETURN_VALUES_H

typedef enum {
    OK,
    NOT_OK,
    NULL_PTR_PASSED,
    MISSING_CLI_PARAMETER,
    UNKNOWN_CLI_OPTION,
    CANT_OPEN_FILE,
    INVALID_FILE_CONTENT,
    INCOMPATIBLE_MATRICES_SIZES
} ret_val;

#endif // RETURN_VALUES_H
